name:   TETyper_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.18
  - biopython=1.81
  - blast=2.15.0
  - bwa=0.7.17
  - pysam=0.22.0
  - python=3.10.13
  - pyvcf=0.6.8
  - samtools=1.18
  - snakemake=7.32.4
  - spades=3.15.5  
